image: rushmash/gcc-arm-embedded-docker:latest

pipelines:
  branches:
    "2.0":
      - step:
          name: Firmware
          script:
            - ./build_ci.sh $BITBUCKET_CLONE_DIR
            - ./deploy_ci.sh $BITBUCKET_CLONE_DIR $BB_UPLOADER_AUTH_STRING $BITBUCKET_REPO_OWNER $BITBUCKET_REPO_SLUG
