pipelines:
  branches:
    "2.0":
      - parallel:
          - step:
              name: Firmware
              image: rushmash/gcc-arm-embedded-docker:latest
              script:
                - ./build_ci.sh firmware $BITBUCKET_CLONE_DIR
                - ./deploy_ci.sh firmware $BITBUCKET_CLONE_DIR $BB_UPLOADER_AUTH_STRING $BITBUCKET_REPO_OWNER $BITBUCKET_REPO_SLUG
          - step:
              name: Software
              image: rushmash/qt-docker:latest
              script:
                - ./build_ci.sh software $BITBUCKET_CLONE_DIR
