# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = MLinkClientTest
DESTDIR = ../../x64/Release
QT += core network gui widgets serialport
CONFIG += release
DEFINES += _UNICODE WIN64 QT_DLL QT_SERIALPORT_LIB QT_WIDGETS_LIB QT_NETWORK_LIB
INCLUDEPATH += ./GeneratedFiles \
    . \
    ./GeneratedFiles/$(ConfigurationName)
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(MLinkClientTest.pri)
win32:RC_FILE = MLinkClientTest.rc
